### ISSUE TITLE
Selected Game Object Destruction of his parent

### ISSUE THREAD

**Issue by Dedado3000** [Horizons-Games/Axolotl-Engine#167]
When a gameObject is deleted in the hierarchy didn't check if the selected gameObject is a child of it

**Comment by markmeliaa** [comment]
Do you mean that when you select a child and then delete its parent without selecting it, the engine breaks?

**Comment by Dedado3000** [comment]
Yes, you can see the soluution that  @DADSILVER and me did at pull request https://github.com/Horizons-Games/Axolotl-Engine/pull/168

**Comment by markmeliaa** [comment]
Nice, good job!

**Comment by markmeliaa** [comment]
Now it is really fixed 🫡
