### ISSUE TITLE
Thread cannot find textures sometimes and causes assertion

### ISSUE THREAD

**Issue by sncarbo** [Horizons-Games/Axolotl-Engine#208]
After several texture loads/removals the thread is not able to find the texture.

<img width="956" alt="texture_error" src="https://user-images.githubusercontent.com/116657602/225708699-9eff31f0-982a-409c-a02b-f556343610b1.png">

**Comment by sncarbo** [comment]
> Could you check that this bug is still happening? I think #246 might have fixed it, but I'd like to be sure before closing this.

It doesn't happen to me anymore. I don't know if it's because I'm lucky or because it's fixed hahaha

**Comment by gerard-queralt** [comment]
Hopefully the latter! I'll close this for now, and if it comes up again we can reopen it.
