### ISSUE TITLE
Selection raycast is broken

### ISSUE THREAD

**Issue by PaablooCH** [Horizons-Games/Axolotl-Engine#285]
you can no longer select a gameobject through the scene

**Comment by markmeliaa** [comment]
:)

**Comment by OriolSors** [comment]
I found the issue

**Comment by markmeliaa** [comment]
> I found the issue, the problem is with the Static and Dynamic objects coming from #274 that didn't take into account for the raycast.

Nice, how do we fix it?

**Comment by OriolSors** [comment]
The idea is to create a similar function in Physics as the AddIntersectionGameObject and AddIntersectionQuadtree that takes into account the Scene::GetNonStaticObjects()

**Comment by markmeliaa** [comment]
esque esto no puede ser, de verdad
