### ISSUE TITLE
Bugs in States Machine

### ISSUE THREAD

**Issue by ericdacal** [Horizons-Games/Axolotl-Engine#331]
I find some bugs using the state machines(not blockers but maybe can be fine to fix after merge with dev):

- Engine crash when you delete a state in Edit State Machine.
- If you change the animation of an state in Edit, and after that you run, Engine crash.

**Comment by gerard-queralt** [comment]
Hi Eric, the first bug should be fixed, test it out whenever you can and let me know if you still encounter it.

**Comment by ericdacal** [comment]
The bug is solved! I close the issue.

Thanks Gerard
