### ISSUE TITLE
Copy shorcuts do infinites copies.

### ISSUE THREAD

**Issue by Vlukkee** [Horizons-Games/Axolotl-Engine#391]
When you mantain pressed control C or D you can do infinite copies. 

![2023-05-18_04h45_02](https://github.com/Horizons-Games/Axolotl-Engine/assets/25518155/1e005c58-2053-415f-8092-f857aecbb711)

**Comment by gerard-queralt** [comment]
Probably same issue: https://app.clickup.com/t/865byk1tz
