### ISSUE TITLE
The windows continue working even if they are not selected.

### ISSUE THREAD

**Issue by Vlukkee** [Horizons-Games/Axolotl-Engine#395]
The windows continue working even if they are not selected.

https://github.com/Horizons-Games/Axolotl-Engine/assets/25518155/1dce0906-46b4-46c9-b086-e4115ac3939e

https://github.com/Horizons-Games/Axolotl-Engine/assets/25518155/186caf6d-9e82-4350-a999-5adb7b254d0c

**Comment by gerard-queralt** [comment]
Second example is a known issue, see https://app.clickup.com/t/865c87n4e.
First one might be related, but I'll take a look.
