### ISSUE TITLE
Duplicate a button component crash the engine

### ISSUE THREAD

**Issue by Vlukkee** [Horizons-Games/Axolotl-Engine#513]
If i try to copy and paste or crtl D a button the engine crash.

Maybe is when the copy system try to copy a 2D object make this because some transform value is null.

![2023-06-21_12h25_01](https://github.com/Horizons-Games/Axolotl-Engine/assets/25518155/47a20511-8c6d-4542-a3b9-772b69aedae3)

**Comment by gerard-queralt** [comment]
Looking at the stack trace, seems we reached `ComponentTransform`, which we never should've. Could be linked to #485, even if there are different causes, they both arrive at the same crash.

**Comment by AuxPort66** [comment]
The last person who change InsertGameObjectAndChildrenIntoSceneGameObjects in Scene.cpp put IsRenderable as a protection to put things on the QuadTree. But UI components are Drawable too and if you put it on the QuadTree explode.

I fixed it in a branch in gameplay, so it will be fixed when gameplay updates develop
