### ISSUE TITLE
Removing an animation in the state editor crash the Engine

### ISSUE THREAD

**Issue by ericdacal** [Horizons-Games/Axolotl-Engine#518]
Use the remove button of animation crash the engine.

![image](https://github.com/Horizons-Games/Axolotl-Engine/assets/16444893/4c45541b-f570-445d-b2e0-68e209523c41)

This is the error:

![image](https://github.com/Horizons-Games/Axolotl-Engine/assets/16444893/4d11559a-de42-4159-a41e-beb657cff5c3)

**Comment by markmeliaa** [comment]
Smh it got fixed
