### ISSUE TITLE
Collisions do not work correctly (sometimes they work and sometimes they don't) and damage is not always correctly dealt because of that

### ISSUE THREAD

**Issue by markmeliaa** [Horizons-Games/Axolotl-Engine#602]
As stated, `OnTriggerEnter` collisions do not work as expected, and when used to deal damage to both the enemies and Bix, they only work half of the time, which results in the execution of the attacks being frustrating because the player would not really know when they will deal damage and when they won't.

**Comment by AuxPort66** [comment]
I can check it
