### ISSUE TITLE
Can not import a scene

### ISSUE THREAD

**Issue by PaablooCH** [Horizons-Games/Axolotl-Engine#674]
I tried to import a scene into another and this error showed up 
![image](https://github.com/Horizons-Games/Axolotl-Engine/assets/62140600/e72bd072-daa1-40c9-b28e-a26d8d102532)

Probably related to load asynchronous.

**Comment by Dedado3000** [comment]
How can i recreate this? I tried to import all the scenes and all was good in developt

**Comment by gerard-queralt** [comment]
> How can i recreate this? I tried to import all the scenes and all was good in developt

Did you make sure to pull the latest changes? For me it was as easy as

1. Start the engine in Release
2. Import BixPrefab
3. Assert as reported

But anyways, this should be fixed now. Sorry about that!!
